- hosts: 127.0.0.1
  connection: local
  tasks:
      - name: Start an Erlang VM
        shell: "erl -sname test@localhost -setcookie cookie -noshell -noinput +Bd \
                -eval \"file:write_file(\\\"erlang.pid\\\", os:getpid()).\" &"

      - name: Execute an RPC call
        erl_rpc: 
            node: test@localhost 
            nametype: shortnames
            cookie: cookie
            module: erlang
            function: system_info
            args: "[otp_release]"
        register: rpc_output

      - debug:
          var: rpc_output.result

      - name: Kill the Erlang VM
        shell: "pkill -F erlang.pid"
